# Generated by Django 5.1.1 on 2024-09-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsteachers',
            old_name='student',
            new_name='students',
        ),
        migrations.RenameField(
            model_name='studentsteachers',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
